token:
  expiration-time: 864000000
  secret: '{cipher}AYCGhtnYslH+tSERLbN+tOQBxTHJ9shhcbj2/b3y65sAlpPLBnG7EjwyuTkgEOGZuCG9AqJjISRjdt1xPb4UNuY7gL2zgUTy9XpfIhaKHGrHE4APfdL0Cuz+dQV2v4oMzXOzUTXnSOpehNhkCJyATuObJKLWxxRainLj3JCME756f6qgw55osYdGLccCkQrqpJEsZ0jf0XwgY6niD/3gZiujGPZNUOMxQrJL6RHULKy4sBX7kibFpVrQQX0DG5i/XpGHAve7d8eHTwMvNhHIN5D93aR1y22A1CAHcyBHOG8R7pKjuXCW7c5R6dhnJmf8yiBJpdgqGQSxmXKDBHaebCtOHQINlCSGXfR7gXX7Cd+PTtJ82S1SPPpTq8mAHoqQhIQpHS9voTjk73Tk2sMY4/xjhfCCD2eVd6pIwFReHhHEUwZO99fFeS0qbiRGKUF68/si24ALe5BCkEseME3siDwVOBmU5V01OO/V61foxHryZjG5EXHC9vhmnHuPxLSm1KntQvIAazFyGa/J7xZDbmGnwLTtB6hiTB1Gkbr+4WlktD/Qge5OXnUzOF3z+ob/Tw2R8fHERWGnDiImYT/5P+3/NPupmWrU8gJsnrDoqHr+cg=='

gateway:
  ip: 192.168.0.7
