### CREATE USER
POST http://localhost:8000/user-service/users
Authorization: Basic user password
Content-Type: application/json

{
  "email": "example@example.com",
  "name": "example",
  "pwd": "1234"
}


### USER LIST
GET http://localhost:8000/user-service/users
Authorization: Basic user password

### USER DETAIL
GET http://localhost:8000/user-service/users/9b52e91c-cb26-4197-8d86-6e38ca920312
Authorization: Basic user password

### CATALOG LIST
GET http://localhost:8000/catalog-service/catalogs

### 주문 넣기
POST http://localhost:8000/order-service/9b52e91c-cb26-4197-8d86-6e38ca920312/orders
Content-Type: application/json

{
  "productId": "CATALOG-003",
  "qty": 10,
  "unitPrice": 1200
}